# Generated by Django 5.2.6 on 2025-11-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=100, unique=True)),
                ('team_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bot_token', models.CharField(max_length=255)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
