# Generated by Django 5.2.6 on 2025-11-01 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_slackinstallation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
